# Generated by Django 5.0.6 on 2026-04-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HHAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название аккаунта')),
                ('username', models.EmailField(max_length=254, verbose_name='Email (логин) HH.ru')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль HH.ru')),
                ('resume_id', models.CharField(blank=True, max_length=255, verbose_name='ID резюме')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('search_filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры поиска')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('auto_apply', models.BooleanField(default=False, verbose_name='Автоотклик')),
                ('max_applications_per_day', models.PositiveIntegerField(default=20, verbose_name='Макс. откликов в день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hh_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт HH.ru',
                'verbose_name_plural': 'Аккаунты HH.ru',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Успешных откликов')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='accounts.hhaccount')),
            ],
            options={
                'verbose_name': 'Лог запуска',
                'verbose_name_plural': 'Логи запусков',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AppliedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.CharField(max_length=255, verbose_name='ID вакансии')),
                ('vacancy_url', models.URLField(verbose_name='URL вакансии')),
                ('vacancy_title', models.CharField(max_length=500, verbose_name='Название вакансии')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_vacancies', to='accounts.hhaccount')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-applied_at'],
                'unique_together': {('account', 'vacancy_id')},
            },
        ),
    ]
